name: VulnCheck
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  vulncheck:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25 # Same as 'go x.y.z' in go.mod
          cache: false
      - name: Get official govulncheck
        shell: bash
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global url."https://minio-bot:${TOKEN}@github.com".insteadOf "https://github.com"
          go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run govulncheck
        run: govulncheck -show verbose -scan package ./...
        shell: bash
